// <auto-generated />
using CES.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CES.Database.Migrations
{
    [DbContext(typeof(CesContext))]
    partial class CesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CES.Database.Models.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new { Id = 1L, Code = "DKO", Name = "DE KANARISKE OER" },
                        new { Id = 2L, Code = "TUN", Name = "TUNIS'" },
                        new { Id = 3L, Code = "SUA", Name = "SUAKIN" },
                        new { Id = 4L, Code = "TAN", Name = "TANGER" },
                        new { Id = 5L, Code = "CAI", Name = "CAIRO" },
                        new { Id = 6L, Code = "KAG", Name = "KAP GUARDAFUI" },
                        new { Id = 7L, Code = "AMA", Name = "AMATAVE" },
                        new { Id = 8L, Code = "MOC", Name = "MOCAMBIQUE" },
                        new { Id = 9L, Code = "KAM", Name = "KAP ST.MARIE" },
                        new { Id = 10L, Code = "KAP", Name = "KAPSTADEN" },
                        new { Id = 11L, Code = "HVA", Name = "HVALBUGTEN" },
                        new { Id = 12L, Code = "HEL", Name = "ST. HELENA" },
                        new { Id = 13L, Code = "SLA", Name = "SLAVEKYSTEN" },
                        new { Id = 14L, Code = "GUL", Name = "GULDKYSTEN" },
                        new { Id = 15L, Code = "SIL", Name = "SIERRA LEONE" },
                        new { Id = 16L, Code = "DAK", Name = "DAKAR" },
                        new { Id = 17L, Code = "MAR", Name = "MARRAKESH" },
                        new { Id = 18L, Code = "SAH", Name = "SAHARA" },
                        new { Id = 19L, Code = "TIM", Name = "TIMBUKTU" },
                        new { Id = 20L, Code = "WAD", Name = "WADAI" },
                        new { Id = 21L, Code = "DAR", Name = "DARFUR" },
                        new { Id = 22L, Code = "CON", Name = "CONGO" },
                        new { Id = 23L, Code = "OMD", Name = "OMDURMAN" },
                        new { Id = 24L, Code = "TRI", Name = "TRIPOLI" },
                        new { Id = 25L, Code = "LUA", Name = "LUANDA" },
                        new { Id = 26L, Code = "KAB", Name = "KABALO" },
                        new { Id = 27L, Code = "VIF", Name = "VICTORIAFALDENE" },
                        new { Id = 28L, Code = "BAG", Name = "BAHREL GHAZAL" },
                        new { Id = 29L, Code = "ADA", Name = "ADDIS ABEBA" },
                        new { Id = 30L, Code = "VIS", Name = "VICTORIASOEN" },
                        new { Id = 31L, Code = "ZAN", Name = "ZANZIBAR" },
                        new { Id = 32L, Code = "DRA", Name = "DRAGEBJERGET" }
                    );
                });

            modelBuilder.Entity("CES.Database.Models.Route", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Destination");

                    b.Property<int>("NumberOfSegments");

                    b.Property<string>("Start");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("CES.Database.Models.RouteConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaxiumWeight");

                    b.Property<string>("PriceBetweenTwoSegments");

                    b.HasKey("Id");

                    b.ToTable("RouteConfigurations");
                });

            modelBuilder.Entity("CES.Database.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
